version: '3'
services:
  selenium:
    image: selenium/hub:4.7
    container_name: selenium-hub
    restart: always
    ports: 
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome1:
    image: selenium/node-chrome
    container_name: chrome1
    shm_size: 2gb
    depends_on:
      - selenium
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always

  chrome2:
    image: selenium/node-chrome
    container_name: chrome2
    shm_size: 2gb
    depends_on:
      - selenium
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always
  app:
    build: 
      context: .
    container_name: back
    restart: always
    volumes:
      - "./app:/app"
    ports: 
      - "4000:4000"
    environment:
      - SELENIUM_URL=http://selenium:4444
    depends_on:
      - selenium
      # - chrome
  # web:
  #   container_name: nginx
  #   build: ./nginx
  #   ports: 
  #     - "80:80"
  #   depends_on:
  #     - app
  #     - frontend
  #   restart: always

  frontend:
    container_name: frontend
    build: ./frontend
    ports: 
      - "3000:3000"
    depends_on:
      - selenium
    restart: always